kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: send_usage_emails
    app.openshift.io/vcs-uri: 'https://github.com/bcgov/nr-optimize-metabase-api'
    openshift.io/generated-by: OpenShiftWebConsole
  selfLink: >-
    /apis/build.openshift.io/v1/namespaces/15be76-tools/buildconfigs/send-usage-emails
  resourceVersion: '1492987957'
  name: send-usage-emails
  uid: 09ffc9c3-bfcb-43f0-b347-16cd2123b7f3
  creationTimestamp: '2021-08-10T23:38:40Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2021-08-12T22:31:57Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/part-of': {}
        'f:spec':
          'f:output':
            'f:to':
              .: {}
              'f:kind': {}
              'f:name': {}
          'f:runPolicy': {}
          'f:source':
            'f:contextDir': {}
            'f:git':
              .: {}
              'f:ref': {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:dockerfilePath': {}
              'f:env': {}
              'f:pullSecret':
                .: {}
                'f:name': {}
            'f:type': {}
          'f:triggers': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2021-08-12T23:01:59Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:lastVersion': {}
  namespace: 15be76-tools
  labels:
    app: send-usage-emails
    app.kubernetes.io/component: send-usage-emails
    app.kubernetes.io/instance: send-usage-emails
    app.kubernetes.io/part-of: send-usage-emails
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'send-usage-emails:latest'
  resources: {}
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 1
  strategy:
    type: Docker
    dockerStrategy:
      pullSecret:
        name: artifactory-creds
      env:
        - name: SMTP_SERVER
          valueFrom:
            secretKeyRef:
              name: send-usage-emails
              key: SMTP_SERVER
        - name: USE_DEBUG_IDIR
          valueFrom:
            secretKeyRef:
              name: send-usage-emails
              key: USE_DEBUG_IDIR
        - name: DEBUG_IDIR
          valueFrom:
            secretKeyRef:
              name: send-usage-emails
              key: DEBUG_IDIR
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: send-usage-emails
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: send-usage-emails
              key: POSTGRES_PASSWORD
      dockerfilePath: send_usage_emails_docker
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/bcgov/nr-optimize-metabase-api'
      ref: send_usage_emails
    contextDir: /send-usage-emails
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: send-usage-emails-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: send-usage-emails-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 21
