all_division_renames = {
    "Associate Deputy Minister's office": "Associate Deputy Minister's Office",
    "Integrated Resource Operations": "Integrated Resource Operations Division",
    "Regional Operations  Division - South Area": "Regional Operations Division - South Area",
    "Rural Opportunities, Tenures and Engineering": "Rural Opportunities, Tenures and Engineering Division",
    "Corporate Services for the Natural Resource Ministries": "Corporate Services for the Natural Resource Sector",
    "Cross Sector Solutions": "Cross Sector Solutions Division",
    "Land Use Policy, Planning and Ecosystem Division": "Land Use Policy, Planning and Ecosystems Division",
    "Land Use Policy, Planning & Ecosystems Division": "Land Use Policy, Planning and Ecosystems Division",
    "Land Use Policy, Planning and Ecosystems Division - Omineca": "Land Use Policy, Planning and Ecosystems Division - Omineca",
    "Natural Resource and Digital Services Division": "Natural Resource Information and Digital Services Division",
    "Natural Resource Information and Digital Service Division": "Natural Resource Information and Digital Services Division",
    "Natural Resource information and Digital Services Division": "Natural Resource Information and Digital Services Division",
    "Natural Resource Sector Sectretariat": "Natural Resource Sector Secretariat",
    "Reconciliation and Natural Resource Sector Policy Division": "Natural Resource Sector Reconciliation and NRS Policy Division",
    "Reconciliation and NRS Policy": "Natural Resource Sector Reconciliation and NRS Policy Division",
    "Reconciliation and NRS Policy Division": "Natural Resource Sector Reconciliation and NRS Policy Division",
    "Natural Resource Sector Reconciliation Policy Division": "Natural Resource Sector Reconciliation and NRS Policy Division",
    "Water, Fisheries and Coastal Policy & Planning Division": "Water, Fisheries and Coastal Policy and Planning Division",
    "BC Parks and Conservation Officer Service": "BC Parks and Conservation Officer Services Division",
    "BC Parks and Conservation Officer Service Division": "BC Parks and Conservation Officer Services Division",
    "BC Parks, Recreation Sites & Trails Division": "BC Parks, Recreation Sites and Trails Division",
    "BC Parks, Recreation, Sites and Trails Division": "BC Parks, Recreation Sites and Trails Division",
    "Climate Action  Secretariat": "Climate Action Secretariat",
    "Climate Action Secretariate": "Climate Action Secretariat",
    "ENV - Environmental Stewardship": "ENV - Environmental Stewardship Division",
    "Environment Assessment Office": "Environmental Assessment Office",
    "Environmental Protection": "Environmental Protection Division",
    "Environmental Protection Divisoin": "Environmental Protection Division",
    "Information, Innovation and Technology Division": "Natural Resource Information and Digital Services Division",
    "Natural Resource Information Digital Services": "Natural Resource Information and Digital Services Division",
    "Land Use Policy, Planning & Ecosystems Division": "Land Use Policy, Planning and Ecosystems Division",
    "Strategic Policy Branch": "Strategic Policy Division",
    "Deputy Minister�s Office": "Deputy Minister's Office",
    "Mines Competitiveness & Authorization Division": "Responsible Mining and Competitiveness Division",
    "Mines Competitiveness and Authorization Division": "Responsible Mining and Competitiveness Division",
    "Mines, Competitiveness & Authorization Division": "Responsible Mining and Competitiveness Division",
    "Mines, Competitiveness and Authorizations Division": "Responsible Mining and Competitiveness Division",
    "Mines Health, Safety & Enforcement Division": "Mines Health, Safety and Enforcement Division",
    "Mines Health, Safety and Enforcement": "Mines Health, Safety and Enforcement Division",
    "Mines, Health, Safety & Enforcement Division": "Mines Health, Safety and Enforcement Division",
    "Oil Infrastructure Group": "Oil and Gas Division",
    "Agriculture Land Commission": "Agricultural Land Commission",
    "Science, Policy and Policy Division": "Science, Policy and Inspection Division",
    "Science Policy and Inspection Division": "Science, Policy and Inspection Division",
    "Negotiations and Regional Operations Branch": "Negotiations and Regional Operations Division",
    "Strategic Partnership and Initiatives Division": "Strategic Partnerships and Initiatives Division",
    "IRR - Strategic Partnerships and Initiatives Division": "Strategic Partnerships and Initiatives Division",
    "SPID - Strategic Partnerships and Initiatives Division": "Strategic Partnerships and Initiatives Division",
    "": "",
}

for_division_acronyms = {
    "Associate Deputy Minister's Office": "ADMO",
    "Associate Deputy Minister's Office, Forest Sector": "ADMO",
    "Assistant Deputy Minister – North Area Office": "ADMO",
    "BC Parks, Recreation Sites and Trails Division": "BCPRST",
    "BC Timber Sales - Seaward-Tlasta": "BCTS-ST",
    "BC Wildfire Service": "BCWS",
    "Climate Action Secretariat": "CAS",
    "Communications": "COMMS",
    "Corporate Services for the Natural Resource Ministries": "CSNR",
    "Corporate Services for the Natural Resource Sector": "CSNR",
    "Cross Sector Solutions Division": "CSS",
    "WLRS - CSSD": "CSS",
    "Deputy Minister's Office": "DMO",
    "Forest Policy and Indigenous Relations Division": "FPIR",
    "Forests Lands and Natural Resources": "FOR",
    "Forests, Lands, Natural Resource Operations & Rural Development": "FOR",
    "Information, Innovation and Technology Division": "NRIDS",
    "Integrated Resource Operations Division": "IROD",
    "Integrated Resources Operations Division": "IROD",
    "Land Use Policy, Planning and Ecosystems Division": "LUPPE",
    "Land use Policy, Planning and Ecosystems Division": "LUPPE",
    "Natural Resource Information and Digital Services Division": "NRIDS",
    "Office of the Chief Forester": "OCF",
    "Operations": "ROD",
    "Regional Operations Division": "ROD",
    "FOR - Regional Operations Division": "ROD",
    "Reginal Operations Division - Coast Area": "ROD-C",
    "Reginal Operations Division - South Area": "ROD-S",
    "REGIONAL OPERATIONS DIVISION South Area": "ROD-S",
    "Regional Operations Division - South Area": "ROD-S",
    "Regional Operations Division - Coast Area": "ROD-C",
    "Regional Operations Division - North Area": "ROD-N",
    "Skeena Region": "ROD-N",
    "Regional Operations Division - South  Area": "ROD-S",
    "Regional Operations Division - South Area": "ROD-S",
    "Regional Operations Division -South Area": "ROD-S",
    "Regional Operations Divison - South Area": "ROD-S",
    "Thompson Okanagan Region": "ROD-S",
    "Resource Stewardship Division": "RSD",
    "Rural Opportunities, Tenures and Engineering Division": "ROTE",
    "South Coast Region": "SCR",
    "Strategic Partnerships and Initiatives Division": "SPI",
    "Timber, Economics and Range Division": "TRE",
    "Timber, Range and Economics Division": "TRE",
    "Tourism Sector Strategy": "TSS",
    "": "Non-Standard",
}

wlrs_division_acronyms = {
    "Associate Deputy Minister's Office": "ADMO",
    "ADM's Office": "ADMO",
    "Climate Action Secretariat": "CAS",
    "Corporate Services for the Natural Resource Sector": "CSNR",
    "Corporate Services for the Natural Resources Ministries": "CSNR",
    "Cross Sector Solutions Division": "CSS",
    "Cross Sector Solutions Divison": "CSS",
    "Deputy Minister's Office": "DMO",
    "Natural Resource Information and Digital Services": "NRIDS",
    "LWRS - Land Use Policy, Planning and Ecosystems Division": "LUPPED",
    "Land Use Policy, Planning and Ecosystems Division": "LUPPED",
    "Land Use Policy, Planning and Ecosystems Division - Omineca": "LUPPED",
    "Land Use Planning, Policy and Ecosystems - Omineca": "LUPPED",
    "NRS Secretariat": "NRSS",
    "Natural Resource Information and Digital Services Division": "NRIDS",
    "Natural Resource Sector Secretariat": "NRSS",
    "Natural Resource Sector Reconciliation and NRS Policy Division": "RNRSP",
    "Regional Operations Division": "ROD",
    "Regional Operations Division - North Area": "ROD-N",
    "Regional Operations Division - South Area": "ROD-S",
    "Rural Opportunities, Tenures and Engineering Division": "ROTE",
    "Strategic Policy Division": "SPD",
    "Water, Fisheries and Coastal Policy and Planning Division": "WFCPP",
    "Water, Fisheries and Coastal Policy & Planning  Division": "WFCPP",
    "": "Non-Standard",
}

env_division_acronyms = {
    "Associate Deputy Minister's Office": "ADMO",
    "BC Parks and Conservation Officer Services Division": "BCPCOS",
    "BC Parks Recreation Sites and Trails Divison": "BCPCOS",
    "BC Parks, Recreation and Sites and Trails Division": "BCPRST",
    "BC Parks, Recreation Sites and Trails Division": "BCPRST",
    "Climate Action Secretariat": "CAS",
    "Compliance and Enforcement Division": "C&E",
    "Compliance and Enforcement  Division": "C&E",
    "Deputy Minister's Office": "DMO",
    "ENV - Environmental Stewardship": "ESD",
    "Environment and Climate Change Strategy": "ECCS",
    "Environmental Assessment Office": "EAO",
    "Environmental Protection": "EPD",
    "Environmental Protection Division": "EPD",
    "Environmental Protection Divisoin": "EPD",
    "Environmental Standards Branch": "ESB",
    "Environmental Sustainability Division": "ESD",
    "Natural Resource Information and Digital Services Division": "NRIDS",
    "Integrated Resource Operations Division": "IROD",
    "Land Use Policy, Planning and Ecosystems Division": "LUPPE",
    "Services & Technology Division": "S&T",
    "Service BC": "CAS",
    "Strategic Policy Division": "SPD",
    "Strategic Services Division": "SSD",
    "": "Non-Standard",
}

emli_division_acronyms = {
    "Deputy Minister's Office": "DMO",
    "Deputy Ministers Office": "DMO",
    "Energy Decarbonization Division": "EDD",
    "Electricity and Alternative Energy Division": "EDD",
    "Electricity and Alternate Energy Division": "EDD",
    "Electricity and Utility Regulation Division": "EDD",
    "LNG Canada Implementation Secretariat": "LNGCIS",
    "Responsible Mining and Competitiveness Division": "RMCD",
    "Mines, Competitiveness & Authorizations Division": "RMCD",
    "Mines Competitiveness & Authorizations Division": "RMCD",
    "Mines Health, Safety and Enforcement Division": "MHSE",
    "Oil and Gas Division": "OGD",
    "Strategic and Indigenous Affairs Division": "SIAD",
    "Woodfibre Implementation Group": "Woodfibre",
    "Energy, Mines and Low Carbon Innovation": "Non-Standard",
    "Environmental Protection Division": "Non-Standard",
    "Information Communication Technologies": "Non-Standard",
    "NRS Secretariat": "Non-Standard",
    "Real Property Division": "Non-Standard",
    "Rural Opportunities, Tenures and Engineering Division": "Non-Standard",
    "Trade & Industry Development": "Non-Standard",
    "": "Non-Standard",
}

af_division_acronyms = {
    "Agricultural Land Commission": "ALC",
    "Agriculture Resource Division": "ARD",
    "Agriculture Science and Policy Division": "ASP",
    "Corporate Services for the Natural Resource Ministries": "CSNR",
    "BC Parks and Conservation Officer Service Division": "BCPCOS",
    "British Columbia Farm Industry Review Board": "BCFIRB",
    "Business Development Division": "BDD",
    "Deputy Minister's Office": "DMO",
    "Environmental Sustainability Division": "ESD",
    "Environmental Protection Division": "EPD",
    "Indigenous and Entrepreneur Services Unit": "IESU",
    "Science, Policy and Inspection Division": "SPI",
    "Regenerative Agriculture and Climate Initiatives Division": "RACID",
    "Regenerative Agriculture and Climate Initiatives": "RACID",
    "Trade & Industry Development Division": "TIDD",
    "": "Non-Standard",
}

irr_division_acronyms = {
    "Declaration Act Secretariat": "DAS",
    "Deputy Minister's Office": "DMO",
    "IRR - Reconciliation Transformation and Strategies Division": "RTS",
    "Indigenous Relations and Reconciliation": "IRR",
    "Negotiations and Regional Operations Division": "NRO",
    "People and Organizational Development": "POD",
    "Office of the Chief Forester": "OCF",
    "Reconciliation Transformation and Strategies Division": "RTS",
    "Regional Operations Division - North Area": "ROD-N",
    "SPP/Indigenous Partnerships": "SPPIP",
    "Strategic Partnerships and Initiatives Division": "SPI",
    "": "Non-Standard",
}

division_acronyms = {
    "FOR": for_division_acronyms,
    "WLRS": wlrs_division_acronyms,
    "ENV": env_division_acronyms,
    "AF": af_division_acronyms,
    "EMLI": emli_division_acronyms,
    "IRR": irr_division_acronyms,
}
