apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: helloworlddemo
  namespace: 15be76-dev
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: helloworlddemo
              image: image-registry.openshift-image-registry.svc:5000/15be76-tools/helloworld-demo:latest
              args:
          restartPolicy: OnFailure
