---
kind: Template
apiVersion: v1
labels:
  app: "${NAME}"
  app.kubernetes.io/component: "${NAME}"
  app.kubernetes.io/instance: "${NAME}"
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/name: java
  app.kubernetes.io/part-of: "${NAME}"
  template: "${NAME}-secret-template"
metadata:
  name: "${NAME}-secret"
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      annotations:
        template.openshift.io/expose-password: "{.data['database-password']}"
        as-copy-of: template.${NAME}-secret
      name: "${NAME}-secret"
    stringData:
      admin-email: "${ADMIN_EMAIL}"
      admin-password: "${ADMIN_PASSWORD}"
      admin-username: "${NAME}-admin"
      database-password: "${DATABASE_PASSWORD}"
      embedding-secret-key: "${EMBEDDING_SECRET_KEY}"
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the objects defined in this template.
    required: true
    value: metabase
  - name: ADMIN_EMAIL
    displayName: Admin Email
    description: The email associated with the metabase admin user
    required: true
  - name: ADMIN_PASSWORD
    displayName: Admin Password
    description:
      The password for the metabase admin user. Requires 2 upper, 2 lower,
      1 special, 1 numeric chars and minimum 8 char length
    generate: expression
    from: "[a-zA-Z0-9]{8}!@#$%^&_[a-zA-Z0-9]{8}"
    required: true
  - name: DATABASE_PASSWORD
    displayName: Database Password
    description:
      A minimum 16 character password that is generated in the target database,
      and then copied over into this field.
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true
  - name: EMBEDDING_SECRET_KEY
    displayName: Embedding Secret Key
    description: A key that is used to embed metabase screens from within a website
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true