---
author: "Copyright: Optimization Team 2022"
date: "Compiled on `r format(Sys.time(), '%B %d, %Y')`"
output: 
  prettydoc::html_pretty:
    theme: "architect"
params:
  data:
    label: "Input file:"
    value: "*.csv"
    input: text
  ministry:
    label: "Ministry Name:"
    value: AF
    input: select
    choices: [AF, EMLI, ENV, FOR, IRR, LWRS]
  path:
    label: "Directory to Search:"
    value: "////////SERVERNAME.idir.bcgov////SF_F[$]/////CONTAINER////SHARE////ROOT_FOLDER////SUB_FOLDER"
    input: text
  folder:
    label: "Folder Name:"
    value: "SFP_Folder"
    input: text
  quarter:
    label: "Quarter:"
    value: Q1
    input: select
    choices: [Q1, Q2, Q3, Q4]
  fiscal:
    label: "Fiscal Year:"
    value: FY21-22
    input: select
    choices: [FY22-23, FY23-24]
  collected:
    label: "datestamp on OCIO file:"
    value: 2022-09-29
    input: text
title: "SFP Enhanced Report on `r params$folder` for `r params$ministry`" 
subtitle: "`r params$quarter` `r params$fiscal` (data collected on `r params$collected`)"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(dbplyr)
library(dplyr)
library(forcats)
library(glue)
library(here)
library(htmltools)
library(knitr)
library(lubridate)
library(openxlsx)
library(scales)
library(stringr)
library(stringi)
library(tidyverse)
library(shiny)
library(zoo)
```

```{r set system environment, include = FALSE}
# This chunk is helpful if you're using an IDE like VS Code
# You can find the correct directory by typing Sys.getenv("RSTUDIO_PANDOC")
Sys.setenv(RSTUDIO_PANDOC="C:/Program Files/RStudio/bin/")
```

```{r apply team logo, echo=FALSE}
htmltools::img(src = knitr::image_uri(file.path(here("scripts"), "GFX_OptimizationLogo-Icon_v2.png")), 
               alt = 'logo', 
               style = 'position:bottom:0; left:0; padding:10px;',
               width = "350px",
               heigth = "350px")
```

```{r load data, include = FALSE}
# load the csv file containing relevant SFP Enhanced data
here::here()
sfp_cols <- c("filename", "filetype", "category", "path", "share", "sizemb", "lastaccessdate", "modificationdate", "creationdate")
sfp_data <- read_csv((here("source", glue("{params$data}", select = sfp_cols, na.strings=c("","NULL")))))
```

```{r functions, include = FALSE}
convert.date <- function(.data) {
format(as.POSIXct(.data,format='%m/%d/%Y %H:%M:%S'),format='%Y-%m-%d')
}

sheet.names <- function(.data) {
addWorksheet(excel, .data)
}

dt.worksheets <- function(x, .data) {
writeDataTable(excel, sheet = x, .data, colNames = TRUE, withFilter = TRUE)
}

freeze.panes <- function(x) {
freezePane(excel, x, firstRow = TRUE)
}
```

```{r, include = FALSE}
refine_search = paste0("\\b", params$path, "\\b")
```

```{r filter results, include = FALSE}
#sfp_filter1 <- filter(sfp_data, grepl({params$path}, path, ignore.case = TRUE)) 
sfp_filter1 <- sfp_data %>% 
  filter(str_starts(path, regex({params$path}, ignore_case=T)))

sfp_filter <- filter(sfp_filter1, grepl(refine_search, path))
```

```{r reshape data, echo = FALSE}
formatted_sfp_data <- sfp_filter %>%
  mutate(sizegb = sizemb / 1000) %>% 
  mutate(sizegb = round(sizegb, 3)) %>% 
  mutate(monthly_cost = sizegb * 2.7) %>% 
  mutate(monthly_cost = round((monthly_cost), 2)) %>% 
  mutate(obj_store_cost = sizegb * 0.07) %>% 
  mutate(object_storage_cost = round((obj_store_cost), 2)) %>% 
  mutate(lastaccessdate = convert.date(lastaccessdate)) %>% 
  mutate(modificationdate = convert.date(modificationdate)) %>% 
  mutate(creationdate = convert.date(creationdate)) %>%
  select(filename, filetype, category, path, sizemb, sizegb, lastaccessdate, modificationdate, creationdate, monthly_cost, obj_store_cost, object_storage_cost)
```

```{r, include = FALSE}
#count total number of files
count_files <- nrow(formatted_sfp_data)
count_files_formatted <- format(count_files, big.mark = ",", scientific = FALSE)
```

```{r calculate share size, include = FALSE}
calculate_sharesize <- formatted_sfp_data %>%
  group_by(filetype) %>% 
  summarize(foldersizegb = sum(sizegb))
```

```{r calculate folder size, include = FALSE}
calculate_folder_size <- formatted_sfp_data %>%
  group_by(path) %>% 
  summarize(foldersizegb = sum(sizegb), foldercost = sum(monthly_cost), objstorcost = sum(obj_store_cost))
```

```{r calculate category size by folder, include = FALSE}
calculate_folder_category_size <- formatted_sfp_data %>%
  group_by(path, filetype, category, monthly_cost, object_storage_cost) %>% 
  summarize(foldersizegb = sum(sizegb))
```

```{r tally files per folder, include = FALSE}
folder_filetally <- formatted_sfp_data %>%
  group_by(path) %>% 
  summarise("number of files" = n())
```

```{r tally unique categories in share, include = FALSE}
share_category_tally <- formatted_sfp_data %>% 
  group_by(category) %>% 
  summarise(amount = n())
```

```{r tally unique categories per folder, include = FALSE}
folder_category_tally <- formatted_sfp_data %>% 
  group_by(category, path) %>% 
  summarise(amount = n()) %>% 
  select(path, category, amount)
```

```{r create table with folder size & file tally, include = FALSE}
table_pathsize_tallyfiles <- inner_join(calculate_folder_size,folder_filetally, by = "path") 
```

```{r create table with folder category size &  tally, include = FALSE}
table_foldersize_tallyfiles <- inner_join(calculate_folder_category_size,folder_filetally,by="path") %>% 
  select(path, category, "number of files", "total_category_sizegb" = foldersizegb, monthly_cost, object_storage_cost)
```

```{r folder depth calculation, include = FALSE}
# count the number of '\'s in each path
table_pathsize_tallyfiles$folderdepth <- (str_count(table_pathsize_tallyfiles$path, "\\\\"))

# count the number of '\'s in the path parameter, subtract 7 from beginning of path (re: escaped backslashes)
omit_depth <- stri_count_fixed(params$path, "\\") - 7

# subtract path parameter count from each path name's count for a folder depth that starts at the desired search folder
table_pathsize_tallyfiles$folderdepth <- table_pathsize_tallyfiles$folderdepth - omit_depth
```

```{r tally folders based on folder depth, include = FALSE}
table_folderdepth_tallyfolders <- table_pathsize_tallyfiles %>%
  group_by(folderdepth) %>% 
  tally(name = "folderdepth_count")
```

```{r folder count, echo = FALSE}
folder_count <- unique(formatted_sfp_data$path)
folder_count <- length(folder_count)
folder_count <- format(folder_count, big.mark = ",", scientific = FALSE)
```

```{r average folder depth, echo = FALSE}
mean_depth <- as.integer(mean(table_pathsize_tallyfiles$folderdepth))
max_depth <- as.integer(max(table_pathsize_tallyfiles$folderdepth))
```

```{r size of entire share in GB, echo = FALSE}
share_size <- sum(table_foldersize_tallyfiles$total_category_sizegb)
sharesize <- format(share_size, big.mark = ",", scientific = FALSE)
```

```{r share cost, echo = FALSE}
# calculated at $2.70 per GB
# tailor this statement to the specific share
sharecost <- sum(share_size) * 2.7
share_cost <- dollar(sharecost)
objstorecost <- sum(share_size) * 0.07
objstore_cost <- dollar(objstorecost)
annualsavings <- sum(sharecost - objstorecost) * 12
annual_savings <- dollar(annualsavings)
```

```{r find duplicate files, include = FALSE}
# find files that are duplicated in both name and size
duplicate_files <- formatted_sfp_data %>% 
  group_by(filename, sizegb) %>% 
  filter( n() > 1 )

duplicate_files_formatted <- duplicate_files %>% 
  select (filename, path, sizegb, monthly_cost, category, lastaccessdate, modificationdate, creationdate) 

duplicate_files_formatted <- duplicate_files_formatted[order(-duplicate_files_formatted$monthly_cost),]
```

```{r duplicates cost, echo = FALSE}
# calculated at $2.70 per GB
dup_cost <- sum(duplicate_files$monthly_cost)
dup_cost <- dollar(dup_cost)

dup_cost_half <- (sum(duplicate_files$monthly_cost)) / 2
dup_cost_half <- dollar(dup_cost_half)
```

```{r find paths with spaces, echo=FALSE}
# count the number of pathnames that have a blank space
pathname_spaces <- table_pathsize_tallyfiles %>%
  filter(str_detect(path, " ")) %>%
  select(path)

# count number of empty folders
spaced_pathname_count <- unique(pathname_spaces$path)
spaced_pathname_count <- length(spaced_pathname_count)
spaced_pathname_count <- format(spaced_pathname_count, big.mark = ",", scientific = FALSE) 
```

```{r determine character length of paths, echo=FALSE}
# count the number of characters in each subfolder path, omitting "\"
table_pathsize_tallyfiles$pathname_length <- stri_length(table_pathsize_tallyfiles$path) - stri_count_fixed(table_pathsize_tallyfiles$path, "\\")

# count the number of Pathnames over 260 characters
sfp_data_long_path <- table_pathsize_tallyfiles %>% 
  filter(pathname_length >= 260) %>% 
  select(path, pathname_length)

long_path_count <- length(sfp_data_long_path$path)
long_path_count <- format(long_path_count, big.mark = ",", scientific = FALSE)
```

```{r drop theses columns for now, include = FALSE}
#leave out pathname length and object storage cost unless asked for
table_pathsize_tallyfiles <- table_pathsize_tallyfiles %>% 
  select (path, "number of files", folderdepth, foldersizegb, foldercost)
```

```{r find files older than 5 yrs, include = FALSE}
# convert the data collected text to date, subtract 5 years
date <- as.Date({params$collected}, "%Y-%m-%d")
dt_less5 <- ymd(date) - years(5)

# files last accessed more than 5 years ago
files_accessed_5plus <- formatted_sfp_data %>% 
  filter(lastaccessdate < dt_less5) %>% 
  select(filename, path, sizegb, monthly_cost, category, lastaccessdate) 

files_accessed_5plus <- files_accessed_5plus[(order(as.Date(files_accessed_5plus$lastaccessdate))),]


# files last modified more than 5 years ago
files_modified_5plus <- formatted_sfp_data %>% 
  filter(modificationdate < dt_less5) %>% 
  select(filename, path, sizegb, monthly_cost, category, modificationdate)

files_modified_5plus <- files_modified_5plus[(order(as.Date(files_modified_5plus$modificationdate))),]
```

```{r count the old files, include = FALSE}
la_count <- nrow(files_accessed_5plus)
lm_count <- nrow(files_modified_5plus)

la_5plus_count <- format(la_count, big.mark = ",", scientific = FALSE)
lm_5plus_count  <- format(lm_count, big.mark = ",", scientific = FALSE)

la_percent <- (la_count / count_files) * 100
lm_percent <- (lm_count / count_files) * 100

la_percent <- format(round(la_percent, 1), nsmall = 1)
lm_percent <- format(round(lm_percent, 1), nsmall = 1)
```

### DISCLAIMER

> -   The source data for this report is collected from the OCIO and does not include any files under 1MB. This is done by design to keep the reports manageable, as including files under 1 MB would increase the report size tenfold.

```{r just the facts, echo = FALSE}
glue('The size of the {params$folder} folder is {share_size} GB.')

glue('There are {folder_count} folders within {params$folder}.')

glue('The average depth in {params$folder} is {mean_depth} folders, and the maximum is {max_depth}.')

knitr::kable(table_folderdepth_tallyfolders, caption = {params$folder})

#glue('There are {spaced_pathname_count} pathnames that contain a blank space in {params$folder}.')

#glue('There are {long_path_count} pathnames over 260 characters in {params$folder}.')

glue('{la_percent}% of files were last accessed over 5 years ago ({la_5plus_count} files).')

glue('{lm_percent}% of files were last modified over 5 years ago ({lm_5plus_count} files).')

glue('The monthly cost of the {params$folder} share is {share_cost}.')

glue('If this data moved to Object Storage, the monthly cost would be {objstore_cost}. 
The annual savings would be {annual_savings}!')

glue('Dupicate files were identified in the {params$folder} folder that total {dup_cost} per month.') 

glue('Removing the duplicates in {params$folder} could save at least {dup_cost_half} per month!')
```

```{r dynamic output name, include = FALSE}
# create output file names based on parameters
output_excel = paste0("SFP_Enhanced_Report_", params$ministry, "_", params$folder, "_", params$quarter, "_", params$fiscal, ".xlsx")
```

```{r write output to Excel file, include = FALSE}
# create workbook
excel <- createWorkbook(output_excel)

# create sheet names
firstSheet = "Folder Details Overview"
secondSheet = "Duplicate Files"
thirdSheet = "Last Accessed 5+ Years"
fourthSheet = "Last Modified 5+ Years"
#fifthSheet = "Folder Details by Category"
#sixthSheet = "Category Details by Size"
#seventhSheet = "Paths with Spaces"
#eighthSheet = "Long Paths"

# add worksheets to workbook
sheet.names(firstSheet)
sheet.names(secondSheet)
sheet.names(thirdSheet)
sheet.names(fourthSheet)
#sheet.names(fifthSheet)
#sheet.names(sixthSheet)
#sheet.names(seventhSheet)
#sheet.names(eighthSheet)

# assign data tables to worksheets, apply filter across all sheets
dt.worksheets(1,table_pathsize_tallyfiles) 
dt.worksheets(2,duplicate_files_formatted)
dt.worksheets(3,files_accessed_5plus)
dt.worksheets(4,files_modified_5plus)
#dt.worksheets(5,table_foldersize_tallyfiles) 
#dt.worksheets(6,table_sharesize_tallyfiles) 
#dt.worksheets(7,pathname_spaces) 
#dt.worksheets(8,sfp_data_long_path)

# freeze top row of all sheets
freeze.panes(1)
freeze.panes(2)
freeze.panes(3)
freeze.panes(4)
#freeze.panes(5)
#freeze.panes(6)
#freeze.panes(7)
#freeze.panes(8)

# set custom column widths for all sheets
setColWidths(excel, sheet = 1, cols = c(1, 2:5), widths = c(75, 20, 20, 20, 20))
# use this line right below if adding object storage costs
# setColWidths(excel, sheet = 1, cols = c(1:6), widths = c(75, 20, 20, 20, 20, 20))
setColWidths(excel, sheet = 2, cols = c(1, 2, 3:8), widths = c(50, 75, 20, 20, 20, 20, 20, 20))
setColWidths(excel, sheet = 3, cols = c(1, 2, 3:8), widths = c(50, 75, 20, 20, 20, 20, 20, 20))
setColWidths(excel, sheet = 4, cols = c(1, 2, 3:8), widths = c(50, 75, 20, 20, 20, 20, 20, 20))
#setColWidths(excel, sheet = 5, cols = c(1:5), widths = c(75, 20, 20, 20, 20))
#setColWidths(excel, sheet = 5, cols = c(1:3), widths = 20)
#setColWidths(excel, sheet = 7, cols = 1, widths = 75)
#setColWidths(excel, sheet = 8, cols = c(1, 2), widths = c(75, 20))

# set currency format on column
sty1 = createStyle(numFmt="$0.00")
addStyle(excel, sheet = 1, sty1, rows=2:(nrow(table_pathsize_tallyfiles)+1), cols=5)
# use this line right below if adding object storage costs
# addStyle(excel, sheet = 1, sty1, rows=2:(nrow(table_pathsize_tallyfiles)+1), cols=6)
#addStyle(excel, sheet = 2, sty1, rows=2:(nrow(table_foldersize_tallyfiles)+1), cols=5)
addStyle(excel, sheet = 2, sty1, rows=2:(nrow(duplicate_files_formatted)+1), cols=4)
addStyle(excel, sheet = 3, sty1, rows=2:(nrow(duplicate_files_formatted)+1), cols=4)
addStyle(excel, sheet = 4, sty1, rows=2:(nrow(duplicate_files_formatted)+1), cols=4)

# save the workbook to file
saveWorkbook(excel, file = here("output", output_excel), overwrite = TRUE)
```