---
author: "Copyright: Optimization Team 2022"
date: "Compiled on `r format(Sys.time(), '%B %d, %Y')`"
output: 
  prettydoc::html_pretty:
    theme: architect
params:
  data:
    label: "Input file:"
    value: "*.csv"
    input: text
  ministry:
    label: "Ministry Name:"
    value: AF
    input: select
    choices: [AF, EMLI, ENV, FOR, IRR, LWRS]
  quarter:
    label: "Quarter:"
    value: Q1
    input: select
    choices: [Q1, Q2, Q3, Q4]
  fiscal:
    label: "Fiscal Year:"
    value: FY22-23
    input: select
    choices: [FY22-23, FY23-24]
  collected:
    label: "datestamp on OCIO file:"
    value: 2022-05-05
    input: text
title: "SFP Enhanced Report for `r params$ministry`" 
subtitle: "`r params$quarter` `r params$fiscal` (data collected on `r params$collected`)"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(dbplyr)
library(dplyr)
library(forcats)
library(glue)
library(here)
library(htmltools)
library(knitr)
library(lubridate)
library(openxlsx)
library(scales)
library(stringr)
library(stringi)
library(tidyverse)
library(shiny)
library(zoo)
```

```{r set system environment, include = FALSE}
# This chunk is helpful if you're using an IDE like VS Code
# You can find the correct directory by typing Sys.getenv("RSTUDIO_PANDOC")
Sys.setenv(RSTUDIO_PANDOC="C:/Program Files/RStudio/bin/pandoc")
```

```{r apply team logo, echo=FALSE}
htmltools::img(src = knitr::image_uri(file.path(here("scripts"), "GFX_OptimizationLogo-Icon_v2.png")), 
               alt = 'logo', 
               style = 'position:bottom:0; left:0; padding:10px;',
               width = "350px",
               heigth = "350px")
```

```{r load data, include = FALSE}
# load the csv file containing relevant SFP Enhanced data
here::here()
sfp_cols <- c("filename", "filetype", "category", "path", "share", "sizemb", "lastaccessdate", "modificationdate", "creationdate")
sfp_data <- read_csv((here("source", glue("{params$data}", select = sfp_cols, na.strings=c("","NULL")))))
```

```{r functions, include = FALSE}
convert.date <- function(.data) {
format(as.POSIXct(.data,format='%m/%d/%Y %H:%M:%S'),format='%Y-%m-%d')
}

sheet.names <- function(.data) {
addWorksheet(excel, .data)
}

dt.worksheets <- function(x, .data) {
writeDataTable(excel, sheet = x, .data, colNames = TRUE, withFilter = TRUE)
}

freeze.panes <- function(x) {
freezePane(excel, x, firstRow = TRUE)
}
```

```{r folder search, include = FALSE}
formatted_sfp_data <- sfp_data %>%
  mutate(folderdepth = str_count(path, "/")-5) %>% 
  mutate(root = word(path, 1, 7, sep = "/")) %>%
  mutate(sizegb = sizemb / 1000) %>% 
  mutate(sizegb = round(sizegb, 3)) %>% 
  mutate(monthly_cost = sizegb * 2.7) %>% 
  mutate(monthly_cost = round((monthly_cost), 2)) %>% 
  mutate(lastaccessdate = convert.date(lastaccessdate)) %>% 
  mutate(modificationdate = convert.date(modificationdate)) %>%
  mutate(creationdate = convert.date(creationdate)) %>%
  select(filename, filetype, share, root, category, path, sizemb, sizegb, folderdepth, lastaccessdate, modificationdate, creationdate, monthly_cost)
```

```{r, include = FALSE}
#count total number of files
count_files <- nrow(sfp_data)
count_files_formatted <- format(count_files, big.mark = ",", scientific = FALSE)
```

```{r root folder file count, include = FALSE}
# count the ministry's SFP files, split out by root folder
root_file_count <- formatted_sfp_data %>% 
  group_by(root) %>% 
  summarise("number of files" = n())

# count the ministry's SFP files, split out by share
share_file_count <- formatted_sfp_data %>% 
  group_by(share) %>% 
  summarise("number of files" = n())
```

```{r calculate SFP size, include = FALSE}
# sum up the size of the ministry's SFP, split out by root folder
root_size <- formatted_sfp_data %>%
  group_by(root) %>% 
  summarize(folder_size_gb = sum(sizegb))

# sum up the size of the ministry's SFP, split out by share
share_size <- formatted_sfp_data %>%
  group_by(share) %>% 
  summarize(folder_size_gb = sum(sizegb))
```

```{r calculate SFP cost, include = FALSE}
# sum up the cost of the ministry's SFP, split out by root folder
root_cost <- formatted_sfp_data %>%
  group_by(root) %>% 
  summarize(monthly_sfp_cost = sum(monthly_cost)) 

# sum up the cost of the ministry's SFP, split out by share
share_cost <- formatted_sfp_data %>%
  group_by(share) %>% 
  summarize(monthly_sfp_cost = sum(monthly_cost)) 
```

```{r create table, include = FALSE}
table_sfp <- left_join(root_file_count, root_size, by = "root") %>%
  left_join(., root_cost, by='root') 

table_sfp_share <- left_join(share_file_count, share_size, by = "share") %>%
  left_join(., share_cost, by='share') 
```

```{r size of entire ministry SFP in GB, include = FALSE}
sfp_size <- sum(formatted_sfp_data$sizegb)
sfp_size <- format(sfp_size, big.mark = ",", scientific = FALSE)
```

```{r SFP cost for entire ministry, include = FALSE}
sfp_cost <- sum(formatted_sfp_data$monthly_cost)
sfp_cost <- format(sfp_cost, big.mark = ",", scientific = FALSE)
```

```{r count total folders, include = FALSE}
# count the number of folders contained in the ministry SFP
sfp_folder_count <- unique(formatted_sfp_data$path)
sfp_folder_count <- length(sfp_folder_count)
sfp_folder_count <- format(sfp_folder_count, big.mark = ",", scientific = FALSE)
```

```{r unique root folder count, include = FALSE}
# count the number of folders contained in the root
root_folder_count <- unique(formatted_sfp_data$root)
root_folder_count <- length(root_folder_count)
root_folder_count <- format(root_folder_count, big.mark = ",", scientific = FALSE)
```

```{r mean & max folder depth, include = FALSE}
mean_depth <- as.integer(mean(formatted_sfp_data$folderdepth))
max_depth <- as.integer(max(formatted_sfp_data$folderdepth))
```

```{r tally folders based on folder depth, include = FALSE}
# count the number of folders for each unique folder depth recorded
folderdepth_tallyfolders <- formatted_sfp_data %>%
  group_by(folderdepth) %>% 
  tally(name = "number of folders")
```

```{r find duplicate files, include = FALSE}
# find files that are duplicated in both name and size
duplicate_files <- formatted_sfp_data %>% 
  group_by(filename, sizegb) %>% 
  filter( n() > 1 )

duplicate_files_formatted <- duplicate_files %>% 
  select (filename, path, sizegb, monthly_cost, category, lastaccessdate, modificationdate, creationdate) 

duplicate_files_formatted <- duplicate_files_formatted[order(-duplicate_files_formatted$monthly_cost),]
```

```{r duplicates cost, echo = FALSE}
# calculated at $2.70 per GB
dup_cost <- sum(duplicate_files$monthly_cost)
dup_cost <- dollar(dup_cost)

dup_cost_half <- (sum(duplicate_files$monthly_cost)) / 2
dup_cost_half <- dollar(dup_cost_half)
```

```{r find files older than 5 yrs, include = FALSE}
# convert the data collected text to date, subtract 5 years
date <- as.Date({params$collected}, "%Y-%m-%d")
dt_less5 <- ymd(date) - years(5)

# files last accessed more than 5 years ago
files_accessed_5plus <- formatted_sfp_data %>% 
  filter(lastaccessdate < dt_less5) %>% 
  select(filename, path, sizegb, monthly_cost, category, lastaccessdate) 

files_accessed_5plus <- files_accessed_5plus[(order(as.Date(files_accessed_5plus$lastaccessdate))),]


# files last modified more than 5 years ago
files_modified_5plus <- formatted_sfp_data %>% 
  filter(modificationdate < dt_less5) %>% 
  select(filename, path, sizegb, monthly_cost, category, modificationdate)

files_modified_5plus <- files_modified_5plus[(order(as.Date(files_modified_5plus$modificationdate))),]
```

```{r count the old files, include = FALSE}
la_count <- nrow(files_accessed_5plus)
lm_count <- nrow(files_modified_5plus)

la_5plus_count <- format(la_count, big.mark = ",", scientific = FALSE)
lm_5plus_count  <- format(lm_count, big.mark = ",", scientific = FALSE)

la_percent <- (la_count / count_files) * 100
lm_percent <- (lm_count / count_files) * 100

la_percent <- format(round(la_percent, 1), nsmall = 1)
lm_percent <- format(round(lm_percent, 1), nsmall = 1)
```

### DISCLAIMER

> -   The source data for this report is collected from the OCIO and does not include any files under 1MB. This is done by design to keep the reports manageable, as including files under 1 MB would increase the report size tenfold.

```{r just the facts, echo = FALSE}
glue('The size of the {params$ministry} SFP is {sfp_size} GB.')

glue('The monthly cost of the {params$ministry} SFP is ${sfp_cost}.')

glue('There are {sfp_folder_count} folders total in {params$ministry} SFP.
     {root_folder_count} of those are top-level (root) folders')

glue('The average depth in {params$ministry} is {mean_depth} folders, and the maximum is {max_depth}.')

knitr::kable(folderdepth_tallyfolders, caption = "SFP Folder Tally")

# glue('There are {count_files_formatted} files in the {params$ministry} SFP')

glue('{la_percent}% of files were last accessed over 5 years ago ({la_5plus_count} files).')

glue('{lm_percent}% of files were last modified over 5 years ago ({lm_5plus_count} files).')

glue('Dupicate files were identified in the {params$ministry} SFP folders that total {dup_cost} per month.') 

glue('Removing the duplicates in {params$ministry} SFP folders could save at least {dup_cost_half} per month!')
```

```{r dynamic output name, include = FALSE}
# create output file name based on parameters
output_excel = paste0("SFP_Enhanced_Report_", params$ministry, "_", params$quarter, "_", params$fiscal, ".xlsx")
```

```{r write output to Excel file, include = FALSE}
# create workbook
excel <- createWorkbook(output_excel)

# create sheet names
firstSheet = "Share Details"
secondSheet = "Root Folder Details"
thirdSheet = "Duplicate Files"
fourthSheet = "Last Accessed 5+ Years"
fifthSheet = "Last Modified 5+ Years"

# add worksheets to workbook
sheet.names(firstSheet)
sheet.names(secondSheet)
sheet.names(thirdSheet)
sheet.names(fourthSheet)
sheet.names(fifthSheet)

# assign data tables to worksheets, apply filter across all sheets
dt.worksheets(1, table_sfp_share)
dt.worksheets(2, table_sfp) 
dt.worksheets(3, duplicate_files_formatted) 
dt.worksheets(4, files_accessed_5plus)
dt.worksheets(5, files_modified_5plus)

# freeze top row of all sheets
freeze.panes(1)
freeze.panes(2)
freeze.panes(3)
freeze.panes(4)
freeze.panes(5)

# set custom column widths for all sheets
setColWidths(excel, sheet = 1, cols = c(1:5), widths = c(75, 20, 20, 20))
setColWidths(excel, sheet = 2, cols = c(1:5), widths = c(75, 20, 20, 20))
setColWidths(excel, sheet = 3, cols = c(1:8), widths = c(50, 75, 20, 20, 20, 20, 20, 20))
setColWidths(excel, sheet = 4, cols = c(1:6), widths = c(50, 75, 20, 20, 20, 20))
setColWidths(excel, sheet = 5, cols = c(1:6), widths = c(50, 75, 20, 20, 20, 20))

# set currency format on column
sty1 = createStyle(numFmt="$0.00")
addStyle(excel, sheet = 1, sty1, rows=2:(nrow(table_sfp)+1), cols=4)
addStyle(excel, sheet = 2, sty1, rows=2:(nrow(table_sfp)+1), cols=4)
addStyle(excel, sheet = 3, sty1, rows=2:(nrow(table_sfp)+1), cols=4)
addStyle(excel, sheet = 4, sty1, rows=2:(nrow(table_sfp)+1), cols=4)
addStyle(excel, sheet = 5, sty1, rows=2:(nrow(table_sfp)+1), cols=4)

# save the workbook to file
saveWorkbook(excel, file = here("output", output_excel), overwrite = TRUE)
```