---
title: "SFP Enhanced Search - Special Report on S40086\\WANSHARE\\ROB"
subtitle: "Q3 - October 2021"
author: "Copyright: Optimization Team 2021"
date: "Compiled on `r format(Sys.time(), '%B %d, %Y')`"
output: 
  prettydoc::html_pretty:
    theme: architect
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dbplyr)
library(dplyr)
library(forcats)
library(glue)
library(here)
library(htmltools)
library(knitr)
library(lubridate)
library(scales)
library(stringr)
library(tidyverse)
library(writexl)
```

```{r apply team logo, echo=FALSE}
htmltools::img(src = knitr::image_uri(file.path(here("scripts"), "GFX_OptimizationLogo-Icon_v2.png")), 
               alt = 'logo', 
               style = 'position:bottom:0; left:0; padding:10px;',
               width = "350px",
               heigth = "350px")
```

```{r set system environment, include = FALSE}
# This chunk is helpful if you're using an IDE like VS Code
# You can find the correct directory by typing Sys.getenv("RSTUDIO_PANDOC")
Sys.setenv(RSTUDIO_PANDOC="C:/Program Files/RStudio/bin/pandoc")
```

```{r load data, include = FALSE}
here::here()
sfp_enhanced <- read_csv(here("source", "2021-10-01_ENV_SFP_Enhanced_Data.csv"), col_names = TRUE)
```

```{r folder search, include = FALSE}
search_folder <- sfp_enhanced %>%
  filter(str_detect(path, "^\\\\\\\\GRADER\\\\S40086\\\\WANSHARE\\\\ROB")) %>%
  filter(str_detect(path,"\\bROB\\b")) %>% 
  select(filename, path, share, sizemb, lastaccessdate, lastmodifieddate) %>%
  mutate(sizegb = sizemb / 1000) %>% 
  mutate(sizegb = round(sizegb, 3)) %>% 
  mutate(lastaccessdate = as_date(lastaccessdate, tz = NULL)) %>% 
  mutate(lastmodifieddate = as_date(lastmodifieddate, tz = NULL)) %>%
  mutate(filetype = str_extract(filename, "[^.]+$")) %>%
  mutate(filetype = tolower(filetype)) %>% 
  mutate(monthly_cost = sizegb * 2.7) %>% 
  mutate(cost = dollar(monthly_cost)) %>% 
  select(filename, filetype, path, sizemb, sizegb, lastaccessdate, lastmodifieddate, monthly_cost, cost)

#head(search_folder)
```

```{r find duplicate files, include = FALSE}
duplicate_files <- search_folder %>% 
  group_by(filename) %>% 
  filter( n() > 1 )

duplicate_files <- duplicate_files %>% 
  group_by(sizemb) %>% 
  filter( n() > 1 ) 
  

duplicate_files_formatted <- duplicate_files %>% 
  select (filename,	filetype,	path,	sizemb,	sizegb,	lastaccessdate,	lastmodifieddate, cost)

#View(duplicate_files_formatted)
```

```{r calculate share size, include = FALSE}
calculate_sharesize <- search_folder %>%
  group_by(filetype) %>% 
  summarize(foldersizemb = sum(sizemb), foldersizegb = sum(sizegb))

#View(calculate_sharesize)
```

```{r calculate folder size, include = FALSE}
calculate_folder_size <- search_folder %>%
  group_by(path) %>% 
  summarize(foldersizemb = sum(sizemb), foldersizegb = sum(sizegb), foldercost = sum(monthly_cost)) %>% 
  mutate(foldercost = dollar(foldercost)) 

#View(calculate_folder_size)
```

```{r calculate filetype size by folder, include = FALSE}
calculate_folder_filetype_size <- search_folder %>%
  group_by(path, filetype) %>% 
  summarize(foldersizemb = sum(sizemb), foldersizegb = sum(sizegb))

#View(calculate_folder_filetype_size)
```

```{r tally files per folder, include = FALSE}
folder_filetally <- search_folder %>%
  group_by(path) %>% 
  summarise("number of files" = n())

#View(folder_filetally)
```

```{r tally unique file types in share, include = FALSE}
share_filetype_tally <- search_folder %>% 
  group_by(filetype) %>% 
  summarise(amount = n()) %>% 
  arrange(desc(amount))

#View(share_filetype_tally)
```

```{r tally unique file types per folder, include = FALSE}
folder_filetype_tally <- search_folder %>% 
  group_by(filetype, path) %>% 
  summarise(amount = n()) %>% 
  select(path, filetype, amount)

#View(folder_filetype_tally)
```

```{r create table with folder size & file tally, include = FALSE}
table_pathsize_tallyfiles <- inner_join(calculate_folder_size,folder_filetally, by = "path") 

#View(table_pathsize_tallyfiles)
```

```{r create table with share file type size & tally, include = FALSE}
table_sharesize_tallyfiles <- inner_join(calculate_sharesize,share_filetype_tally,by="filetype") %>% 
  select(filetype, amount, foldersizemb, foldersizegb)

#View(table_sharesize_tallyfiles)
```

```{r create table with folder file type size & file type tally, include = FALSE}
table_foldersize_tallyfiles <- inner_join(calculate_folder_filetype_size,folder_filetally,by="path") %>% 
  select(path, filetype, "number of files", "total_filetype_sizemb" = foldersizemb, "total_filetype_sizegb" = foldersizegb)

#View(table_foldersize_tallyfiles)
```

```{r calculate folder depth, include = FALSE}
# Count the number of '\'s in each element of string
table_pathsize_tallyfiles$folderdepth <- str_count(table_pathsize_tallyfiles$path, "\\\\") 
# Subtract 6 because the folder depth count starts after \\GRADER\S40086\WANSHARE\ROB\
table_pathsize_tallyfiles$folderdepth <- table_pathsize_tallyfiles$folderdepth - 6

#View(table_pathsize_tallyfiles)
```

```{r tally folders based on folder depth, include = FALSE}
table_folderdepth_tallyfolders <- table_pathsize_tallyfiles %>%
  group_by(folderdepth) %>% 
  tally(name = "folderdepth_count")

#View(table_folderdepth_tallyfolders)
```

```{r folder count, echo = FALSE}
# tailor this statement to the specific path
folder_count <- unique(search_folder$path)
folder_count <- length(folder_count)

glue('The path \\\\GRADER\\S40086\\WANSHARE\\ROB has {folder_count} folders.')
```

```{r average folder depth, echo = FALSE}
# tailor this statement to the specific path
mean_depth <- as.integer(mean(table_pathsize_tallyfiles$folderdepth))

glue('The average folder depth within \\\\GRADER\\S40086\\WANSHARE\\ROB is {mean_depth}.')
```

```{r size of entire share in GB, echo = FALSE}
# tailor this statement to the specific path
share_size <- sum(table_foldersize_tallyfiles$total_filetype_sizegb)

glue('The size of path \\\\GRADER\\S40086\\WANSHARE\\ROB is {share_size} GB.')
```

```{r share cost, echo = FALSE}
# calculated at $2.70 per GB
# tailor this statement to the specific path
share_cost <- sum(share_size) * 2.7
share_cost <- dollar(share_cost)

glue('The cost of path \\\\GRADER\\S40086\\WANSHARE\\ROB is {share_cost}.')
```

```{r duplicates cost, echo = FALSE}
# calculated at $2.70 per GB
dup_cost <- sum(duplicate_files$monthly_cost)
dup_cost <- round((dup_cost), 2)

dup_cost_half <- dup_cost / 2
dup_cost_half <- round((dup_cost_half), 2)

glue('There are files saved in more than one location on \\\\GRADER\\S40086\\WANSHARE\\ROB that total a cost of ${dup_cost}. 
     By finding & removing all the duplicates, at least half this amount (${dup_cost_half}) could be saved!')
```

```{r write output to Excel file, include = FALSE}
write_xlsx(list("Path Details" = table_pathsize_tallyfiles, "Folder File Type Tally" = table_foldersize_tallyfiles, "Overall File Type Tally" = table_sharesize_tallyfiles, "Folder Depth Tally" = table_folderdepth_tallyfolders, "Duplicate Files" = duplicate_files_formatted), path = here("output","S40086_WANSHARE_ROB_info_Q3_Oct2021.xlsx"))
```